### ISSUE TITLE
Allow on multiple monitors and make falling texts disappear from the bottom of the screen

### ISSUE THREAD

**Issue by joezhouchenye** [torculus/DownFall#10]
Just as the title said, could you add the feature to support downfall on multiple monitors at the same time?

Also, currently, I can see texts fade on the screen. Could you make the texts just disappear outside the screen like truly falling down?

**Comment by torculus** [comment]
Sure, both of those sound like they should be fairly easy to implement :+1:

**Comment by torculus** [comment]
Quick update: managed to implement both of these, but the code needs some cleaning up before I commit into the main branch. Expect an updated extension sometime next week!

**Comment by torculus** [comment]
Okay, the features have both been implemented! :rocket:
