### ISSUE TITLE
this.pane3d is undefined

### ISSUE THREAD

**Issue by ruxbo** [torculus/DownFall#13]
![IMG_20231214_221331020_AE.jpg](https://github.com/torculus/DownFall/assets/143314588/e47b96af-9959-4258-b057-358ce68bec66)

sorry, i'm back 🤪
when i said i'll stress test it, i did locking and opening my laptop, it was ok
i manually suspended my laptop by pressing the power button and it disappeared in the sys-dropdown.

**Comment by torculus** [comment]
Hey @ruxbo ,

So as it turns out, suspend/hibernate/sleep is controlled by `systemd` or whatever else you use as the init system. I asked around, but I'm not sure how to solve this on your end. On [my system](https://knowyourmeme.com/memes/btw-i-use-arch), DownFall resumes normally after suspend/hibernate/sleep.

So I think I'll put a "needs help" on this and keep looking for a solution :smiling_face_with_tear:

**Comment by marcinjahn** [comment]
Alright, now I get it - to actually enable the effect, you need to do it via Quick Settings Panel. I wouldn't figure that out without looking into the code :) I guess it'd make sense to add it to readme (and to https://extensions.gnome.org/ description, if it's not written there)

**Comment by torculus** [comment]
Okay, I just merged your pull request and I'll see if it resolves things. I also agree that some documentation on enabling it would be helpful, and I can add that to the README and EGO

**Comment by torculus** [comment]
Hey @ruxbo , there is a potential fix in the latest version (36) now on extensions.gnome.org

Would you mind updating and then test to see if it's still happening?

**Comment by ruxbo** [comment]
> Hey @ruxbo , there is a potential fix in the latest version (36) now on extensions.gnome.org
> 
> Would you mind updating and then test to see if it's still happening?

hi!
while my extension manager is crashing [when opening the settings] i got it update to version 36 or 4.2.1
i'll do a stress test.
but so far so good.
i locked my desktop, got back in and no error on the extmgr.
i'll post back the results.

thank you!

**Comment by ruxbo** [comment]
> > Hey @ruxbo , there is a potential fix in the latest version (36) now on extensions.gnome.org
> > 
> > Would you mind updating and then test to see if it's still happening?
> 
> hi!
> while my extension manager is crashing [when opening the settings] i got it update to version 36 or 4.2.1
> i'll do a stress test.
> but so far so good.
> i locked my desktop, got back in and no error on the extmgr.
> i'll post back the results.
> 
> thank you!
> 

that did it(?)!
i closed the lid and left it for like 3hrs
open it back up and the button switch still on the system tray
enabled it and it's doing it and the error is gone

i'm big on the 80s, but the matrix capped the 90s
i love this extension

thank you!

**Comment by torculus** [comment]
Excellent! I'll close this for now, but please open another issue if you have any more issues moving forward
