### ISSUE TITLE
this.pane3d is null

### ISSUE THREAD

**Issue by ruxbo** [torculus/DownFall#9]
T440s
Fedora 39

hi!
if i re-install it, it works
then, if my box goes to sleep when i close the lid or even locks after 10mins, the button disappears in the system dropdown and i get the subject if i check it in the exyension gui
thank you

**Comment by torculus** [comment]
Hey @ruxbo, thanks for bringing this to my attention! I'll check into it later today

In the meantime, `this.pane3d` is either the `global.top_window_group` or `Main.layoutManager._backgroundGroup`

When you lock the screen/put your computer to sleep, is the extension running (i.e. snowing/falling/etc.)? That should help me start looking at where to debug

**Comment by ruxbo** [comment]
it's not even running, nothing is falling 😃
as the box goes to sleep or just lock the desktop, it'll just disappear from the system menu
when i look at it in the extension manager, i see that error
but if i restart my laptop or reinstall the ext, it'll be normal

my apologies, i can point-and-click and follow directions but i'm not that good in linux
If there's a log i can trace lemme know

thank you

**Comment by torculus** [comment]
Hey @ruxbo , would you mind checking this again? I think Fedora should now be on GNOME 45.2, and so maybe it was an upstream bug?

**Comment by torculus** [comment]
Update: DownFall now turns off when the screen is locked, so I managed to fix half of this issue. I have an idea for fixing sleep/suspend, but I'll have to get to it later this week

**Comment by torculus** [comment]
So DownFall is now stopping on suspend (aka "sleep") and lock. I also re-worked the logic so that `this.pane3d` is never `null`. This should fix the issue, and I'll upload the revised code to [https://github.com/torculus/DownFall](https://github.com/torculus/DownFall) shortly

Please let me know if you still encounter this issue afterwards, and thanks for opening an issue here!

**Comment by ruxbo** [comment]
i'll do a stress test and brb on that
thank you
